### ISSUE TITLE
[Suggestion] Remove infolayer files from template

### ISSUE THREAD

**Issue by ZenJakey** [iwatkot/maps4fs#26]
GE seems to make them if they're not there. Using ones from the base map end up using the lower resolution if you're not using a 2km map, making the resolution rather bad

**Comment by ZenJakey** [comment]
Actually, seems like blank .pngs are needed for each infolayer

**Comment by iwatkot** [comment]
@ZenJakey, so the suggestion is to remove them from the template? But what about blank pngs? I can't see any pngs for infolayers.

**Comment by LaxZ** [comment]
Wouldn't recommend to do that. I think many beginners use this tool too and don't need to change the resolution of the infolayers. Maybe a info about that in the readme wouldn't be bad. If they want for example a finer grid for creating farmlands, they have to set the resolution to 2048 or 4096 for example. Otherwise, this tool is not an tutorial for creating maps, so yea - removing the infoslayers is not a good idea.

**Comment by iwatkot** [comment]
@LaxZ, hey!

Thanks for sharing your thoughts. Tbh, I have the same concerns about that.

So, I don't think I will do it right now as well as adding this to the repo's documentation. It's a nice thing to know and tell other modders, but I'm kinda scared of REAME turning into a large storage of nonstructured guides.
I assumed that the repo's README should contain all the required information, but nothing else. Because at some point it becomes a pile of outdated tutorials where the newcomer will be lost as in a maze. :D

@ZenJakey, so I'm gonna close it right now. But if you have some information, I think that it would be better if you make a separate repository for MD files about such things. But it should be structured from the beginning, otherwise it will be a mess in a while. We also can use GitBooks later on in this repo to create cool documentation.

Thank you, guys.

Sincerely
