### ISSUE TITLE
Map unable to be opened in giants editor

### ISSUE THREAD

**Issue by Scarboy17** [iwatkot/maps4fs#6]
Hi i used your map generation through telegram for a 4x4 map and as soon as i open it in giants editor it closes any help would be great thankyou.

**Comment by iwatkot** [comment]
@Scarboy17, hello!

Could you please share the following:

1. Map coordinates.
2. Map height (flatlands, mountains, etc.).

Thank you 
Sincerely

**Comment by Scarboy17** [comment]
Hi map coordinates are

-31.298407071320973, 118.88522712789259

And have tried the for plains and for hills with the same result

**Comment by iwatkot** [comment]
@Scarboy17, ok, thank you.
I'll investigate the issue and get back to you.

Sincrely

**Comment by iwatkot** [comment]
@Scarboy17, I can confirm that the issue is recurring and found the cause of this problem - it's missing the DEM file because the SRTM tile was not downloaded.
I don't think I'll investigate the SRTM downloads too much, but I'll add a simple check if it was not downloaded the empty file will be created and the map will be opened in the Giants Editor.

I think that the new release will be ready in a couple of days (hopefully, today).

Sincerely

**Comment by iwatkot** [comment]
You can use the bot to generate your map now.
The new version of the software was released on GitHub too.

FYI: the map for these coordinates will not contain DEM data, since for some reason I can't download the correct image for this place and at the moment I'll not investigate the issues with SRTM data.

**Comment by iwatkot** [comment]
@Scarboy17, thanks to your report, I've identified the issue with SRTM tile names and fixed it.
The new version of the software, including the bot, should generate a height map (DEM) for your coordinates too.

Thanks for the report!
Sincerely
