### ISSUE TITLE
Dem is Black

### ISSUE THREAD

**Issue by TommyGFX** [iwatkot/maps4fs#74]
Hello,

the dem Image is black.

No Greyscale.

48.3028180, 12.5043367

**Comment by TommyGFX** [comment]
- 48.3028180, 12.5043367
- 2048x2048
- no auto preset
- field padding 2
- no error message
-
![map4fs1](https://github.com/user-attachments/assets/ae101e65-62d3-4ebd-ac0d-0e7ca1d86d26)
![map4fs2](https://github.com/user-attachments/assets/5f970368-8806-495e-87a3-f8514f153c23)

**Comment by iwatkot** [comment]
@TommyGFX, hello!

Thanks for reaching out.
When disabling the auto preset feature, please pay attention to the message in the UI.

![image](https://github.com/user-attachments/assets/2e1e20de-cc85-4710-b546-267db681a886)

https://github.com/user-attachments/assets/c8651542-820b-4858-8fe0-f71f5532a717

**Comment by TommyGFX** [comment]
thats right.

in the giants editor no high

**Comment by iwatkot** [comment]
@TommyGFX, yes, and "no high" in GE is an expected behavior.
Learn the basics of working with DEM and how it works in GE in the docs: https://github.com/iwatkot/maps4fs/blob/main/docs/dem.md

Basically, you need to change the Height scale value: https://github.com/iwatkot/maps4fs/blob/main/docs/dem.md

To be honest,  the "right" DEM is black, which you actually received. Auto preset just processes it for beginners. While advanced settings are supposed to be useful for users, who know how GE works.

Regards
